# Generated by Django 5.2.4 on 2025-08-30 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FireIncident',
            fields=[
                ('incident_id', models.AutoField(primary_key=True, serialize=False)),
                ('incident_type', models.CharField(choices=[('Building', 'Building on Fire'), ('Market', 'Market on Fire'), ('Vehicle', 'Vehicle on Fire'), ('Others', 'Others')], help_text='The type of fire incident.', max_length=50)),
                ('severity_level', models.CharField(choices=[('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low')], help_text='The severity of the fire.', max_length=10)),
                ('is_duplicate', models.BooleanField(default=False, help_text='Flag if the report is a potential duplicate.')),
                ('address', models.TextField(help_text='Full address of the incident.')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, help_text='Latitude of the incident location.', max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, help_text='Longitude of the incident location.', max_digits=9, null=True)),
                ('reported_date', models.DateField(auto_now_add=True)),
                ('reported_time', models.TimeField(auto_now_add=True)),
                ('casualties', models.IntegerField(default=0, help_text='Total number of casualties (injured + fatalities).')),
                ('number_of_injured', models.IntegerField(default=0, help_text='Number of people injured.')),
                ('area_affected', models.DecimalField(blank=True, decimal_places=2, help_text='The estimated area affected in sqm.', max_digits=10, null=True)),
                ('estimated_damage', models.DecimalField(blank=True, decimal_places=2, help_text='Estimated monetary value of the damage.', max_digits=12, null=True)),
                ('property_type', models.CharField(blank=True, choices=[('Residential', 'Residential'), ('Market', 'Market'), ('Commercial', 'Commercial'), ('Bushland', 'Bushland'), ('Industrial', 'Industrial'), ('Vehicle', 'Vehicle'), ('Construction', 'Construction')], help_text='The type of property affected by the fire.', max_length=50, null=True)),
                ('cause_of_fire', models.CharField(blank=True, choices=[('Electrical fault', 'Electrical fault'), ('Cooking accident', 'Cooking accident'), ('Bush burning', 'Bush burning'), ('Arson', 'Arson'), ('Overloaded circuit', 'Overloaded circuit'), ('Candle', 'Candle'), ('Fuel spill', 'Fuel spill'), ('Cigarette', 'Cigarette'), ('Spontaneous combustion', 'Spontaneous combustion'), ('Faulty appliance', 'Faulty appliance'), ('Gas leak', 'Gas leak')], help_text='The cause of the fire.', max_length=50, null=True)),
                ('response_time_minutes', models.IntegerField(blank=True, help_text='Time in minutes from report to resolution.', null=True)),
            ],
            options={
                'db_table': 'fire_incidents',
            },
        ),
    ]
