# Generated by Django 5.2.4 on 2025-09-01 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emergency_reports', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccidentIncident',
            fields=[
                ('incident_id', models.AutoField(primary_key=True, serialize=False)),
                ('incident_type', models.CharField(choices=[('Vehicle Collision', 'Vehicle Collision'), ('Motorbike Accident', 'Motorbike Accident'), ('Truck Overturn', 'Truck Overturn'), ('Others', 'Others')], help_text='The type of accident incident.', max_length=50)),
                ('severity_level', models.CharField(choices=[('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low')], help_text='The severity of the accident.', max_length=10)),
                ('status', models.CharField(choices=[('Reported', 'Reported'), ('Investigating', 'Investigating'), ('Resolved', 'Resolved')], default='Reported', help_text='The current status of the incident.', max_length=20)),
                ('is_duplicate', models.BooleanField(default=False, help_text='Flag if the report is a potential duplicate.')),
                ('address', models.TextField(help_text='Full address of the incident.')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, help_text='Latitude of the incident location.', max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, help_text='Longitude of the incident location.', max_digits=9, null=True)),
                ('reported_date', models.DateField(auto_now_add=True)),
                ('reported_time', models.TimeField(auto_now_add=True)),
                ('casualties', models.IntegerField(default=0, help_text='Total number of casualties (injured + fatalities).')),
                ('number_of_injured', models.IntegerField(default=0, help_text='Number of people injured.')),
                ('area_affected', models.DecimalField(blank=True, decimal_places=2, help_text='The estimated area affected in sqm.', max_digits=10, null=True)),
                ('estimated_damage', models.DecimalField(blank=True, decimal_places=2, help_text='Estimated monetary value of the damage.', max_digits=12, null=True)),
                ('property_affected', models.CharField(blank=True, choices=[('Road', 'Road'), ('Bridge', 'Bridge'), ('Intersection', 'Intersection'), ('Expressway', 'Expressway'), ('Toll Gate', 'Toll Gate'), ('Rural Area', 'Rural Area'), ('Gate', 'Gate'), ('Others', 'Others')], help_text='The type of property affected by the accident.', max_length=50, null=True)),
                ('accident_cause', models.CharField(blank=True, choices=[('Speeding', 'Speeding'), ('Pothole', 'Pothole'), ('Brake Failure', 'Brake Failure'), ('Driver Distraction', 'Driver Distraction'), ('Poor Visibility', 'Poor Visibility'), ('Traffic Light Violation', 'Traffic Light Violation'), ('Improper Lane Change', 'Improper Lane Change'), ('Mechanical Failure', 'Mechanical Failure'), ('Animal Crossing', 'Animal Crossing'), ('Drunk Driving', 'Drunk Driving'), ('Tyre Burst', 'Tyre Burst'), ('Others', 'Others')], help_text='The cause of the accident.', max_length=50, null=True)),
                ('number_of_vehicles_affected', models.IntegerField(default=0, help_text='The number of vehicles involved in the accident.')),
                ('response_time_minutes', models.IntegerField(blank=True, help_text='Time in minutes from report to resolution.', null=True)),
            ],
            options={
                'db_table': 'accident_incidents',
            },
        ),
        migrations.AddField(
            model_name='fireincident',
            name='number_of_properties_affected',
            field=models.IntegerField(default=0, help_text='The number of properties involved in the fire.'),
        ),
        migrations.AddField(
            model_name='fireincident',
            name='status',
            field=models.CharField(choices=[('Reported', 'Reported'), ('Investigating', 'Investigating'), ('Resolved', 'Resolved')], default='Reported', help_text='The current status of the incident.', max_length=20),
        ),
    ]
