# Generated by Django 5.2.4 on 2025-09-04 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emergency_reports', '0003_accidentmedia_customuser_firemedia'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmergencyVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_id', models.CharField(help_text="The unique YouTube video ID (e.g., dQw4w9WgXcQ) found in the video's URL.", max_length=50, unique=True)),
                ('title', models.CharField(help_text='The title of the video.', max_length=200)),
                ('description', models.TextField(blank=True, help_text='A brief description of the video content.')),
                ('video_type', models.CharField(choices=[('fire', 'Fire'), ('accident', 'Accident')], help_text='The type of video: fire or accident.', max_length=10)),
                ('category', models.CharField(choices=[('fire_medical', 'Fire: Medical'), ('fire_preparedness', 'Fire: Preparedness'), ('fire_prevention', 'Fire: Prevention'), ('fire_responds', 'Fire: Responds'), ('accident_driving_safety', 'Accident: Driving Safety'), ('accident_emergency_responds', 'Accident: Emergency Responds'), ('accident_motorcycle_safety', 'Accident: Motorcycle Safety'), ('accident_pedestrian_safety', 'Accident: Pedestrian Safety')], help_text='The specific category of the video, such as medical or driving safety.', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='The date and time the video was added to the database.')),
            ],
            options={
                'verbose_name_plural': 'Emergency Videos',
                'ordering': ['-created_at'],
            },
        ),
    ]
