# Generated by Django 5.2.4 on 2025-09-07 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emergency_reports', '0004_emergencyvideo'),
    ]

    operations = [
        migrations.AddField(
            model_name='accidentincident',
            name='additional_info',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fireincident',
            name='additional_info',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='firemedia',
            name='image_url',
            field=models.URLField(help_text='The public URL of the image from Supabase Storage.', max_length=500),
        ),
    ]
