# Generated by Django 5.2.4 on 2025-09-08 15:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emergency_reports', '0006_alter_accidentincident_severity_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accidentmedia',
            name='incident',
            field=models.ForeignKey(help_text='The accident incident this media is associated with.', on_delete=django.db.models.deletion.CASCADE, related_name='media', to='emergency_reports.accidentincident'),
        ),
        migrations.AlterField(
            model_name='accidentmedia',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, help_text='The date and time the media was uploaded.'),
        ),
        migrations.AlterField(
            model_name='firemedia',
            name='incident',
            field=models.ForeignKey(help_text='The fire incident this media is associated with.', on_delete=django.db.models.deletion.CASCADE, related_name='media', to='emergency_reports.fireincident'),
        ),
        migrations.AlterField(
            model_name='firemedia',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, help_text='The date and time the media URL was saved.'),
        ),
    ]
