# Generated by Django 5.2.4 on 2025-09-08 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emergency_reports', '0007_alter_accidentmedia_incident_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fireincident',
            name='severity_level',
            field=models.CharField(choices=[('High Severity', 'High Severity'), ('Medium Severity', 'Medium Severity'), ('Low Severity', 'Low Severity')], help_text='The severity of the accident.', max_length=50),
        ),
    ]
